-- MySQL Workbench Synchronization
-- Generated: 2017-01-26 07:03
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: User

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `user` 
ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT '0' AFTER `flags`,
ADD COLUMN `deleted_at` TIMESTAMP NULL DEFAULT NULL AFTER `deleted`,
ADD COLUMN `deleted_by` BINARY(16) NULL DEFAULT NULL AFTER `deleted_at`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
